Add a test for tagging colour images encoded by opencv
tgRobotics/Library-EXIFTags pull request #13
Opened 2021-06-09 16:10 UTC by mrupes

Adds a test to caputure a bug that was discovered when testing the
ViewLS datatool v5.4.0.

Confirmed that versions  prior to
34957e51cc400488b8b95a95ffa4302e9ff64e231 fail to pass this test.

2021-06-09 16:21 UTC, ryancwicks requested changes

2021-06-09 16:21 UTC, ryancwicks commented on tests/TestImageHandler.cpp
> +
Add a test where you save the image again, and then reload it to ensure that tagging works for saved imags too.

2021-06-09 18:13 UTC, ryancwicks approved these changes

2021-06-10 13:15 UTC, smacdonald-2gr approved these changes

2021-06-10 13:55 UTC, merged